In [1]:
import pandas as pd

summer = pd.read_csv('summer.csv')
summer

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [ ]:
# row index position in this dataset is numbers starting from 0

In [7]:
summer.loc[0]

Year                    1896
City                  Athens
Sport               Aquatics
Discipline          Swimming
Athlete        HAJOS, Alfred
Country                  HUN
Gender                   Men
Event         100M Freestyle
Medal                   Gold
Name: 0, dtype: object

In [10]:
summer.loc[:, 'Year']

0        1896
1        1896
2        1896
3        1896
4        1896
         ...
31160    2012
31161    2012
31162    2012
31163    2012
31164    2012
Name: Year, Length: 31165, dtype: int64

In [3]:
summer.loc[0, 'Country']

'HUN'

In [4]:
summer.loc[[0, 1, 2], 'Country']

0    HUN
1    AUT
2    GRE
Name: Country, dtype: object

In [6]:
summer.loc[[0, 1, 2], ['Athlete', 'Country']]

             Athlete Country
0      HAJOS, Alfred     HUN
1   HERSCHMANN, Otto     AUT
2  DRIVAS, Dimitrios     GRE

In [14]:
summer = summer.set_index('Athlete')
summer

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [15]:
summer.loc['NEUMANN, Paul']

Year                    1896
City                  Athens
Sport               Aquatics
Discipline          Swimming
Country                  AUT
Gender                   Men
Event         400M Freestyle
Medal                   Gold
Name: NEUMANN, Paul, dtype: object

In [17]:
summer.loc['PHELPS, Michael']

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,100M Butterfly,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,200M Butterfly,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,200M Freestyle,Bronze
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,200M Individual Medley,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,400M Individual Medley,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,4X100M Freestyle Relay,Bronze
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,4X100M Medley Relay,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,4X200M Freestyle Relay,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,100M Butterfly,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,200M Butterfly,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,200M Freestyle,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,200M Individual Medley,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,400M Individual Medley,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,4X100M Freestyle Relay,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,4X100M Medley Relay,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,4X200M Freestyle Relay,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,100M Butterfly,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,200M Butterfly,Silver
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,200M Medley,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,4X100M Freestyle,Silver
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,4X100M Medley,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,4X200M Freestyle,Gold